[package]
name = "dining-philosophers"
version = "0.1.0"
authors = ["Michael King <mking@hey.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
ansi_term = "0.12"
